# Generated by Django 4.1.6 on 2023-03-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdp',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
